version: '3.0'

services:
  frontend-service:
    container_name: weather-forecast-app
    image: weather-forecast-app
    build: .
    command: 
      - sh 
      - -c 
      - npm start
    ports:
      - 4200:4200
      - 49153:49153
    volumes:
      - ./:/weather-forecast-app
      - /weather-forecast-app/node_modules

volumes:
  weather-forecast-app: